name: test_ono
on: [push]
jobs:
  echo-teamkoryuu-name:
    runs-on:ubuntu-latest
    steps:
      - run : echo "ono"
      - run : echo "nigoh"
      - run : echo "iwaya"
      - run : echo "hosoda"
      - run : echo "tureta"
